const fs = require('fs');
const path = require('path');
const { createClient } = require(path.resolve(__dirname, '../node_modules/@supabase/supabase-js'));

let supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
let supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  try {
    const envPath = path.resolve(__dirname, '../.env.local');
    if (fs.existsSync(envPath)) {
      const envContent = fs.readFileSync(envPath, 'utf8');
      envContent.split('\n').forEach(line => {
        const match = line.match(/^\s*([^#=]+)\s*=\s*(.*)$/);
        if (match) {
          const key = match[1].trim();
          let val = match[2].trim();
          if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
            val = val.substring(1, val.length - 1);
          }
          if (key === 'NEXT_PUBLIC_SUPABASE_URL') supabaseUrl = val;
          if (key === 'SUPABASE_SERVICE_ROLE_KEY') supabaseServiceKey = val;
        }
      });
    }
  } catch (e) {
    console.error('Error reading .env.local:', e);
  }
}

if (!supabaseUrl || !supabaseServiceKey) {
  console.error("Missing Supabase credentials in process.env or .env.local!");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Define 16 categories requested
const categoriesToSeed = [
  { id: "hr-qiwa", name_ar: "خدمات الموارد البشرية وقوى", name_en: "HR & Qiwa Services", icon: "Activity", order: 10 },
  { id: "commerce-business", name_ar: "خدمات وزارة التجارة ومركز الأعمال", name_en: "MoC & Business Center Services", icon: "Briefcase", order: 20 },
  { id: "municipality-balady", name_ar: "خدمات البلدية ومنصة بلدي", name_en: "Municipal & Balady Services", icon: "Building", order: 30 },
  { id: "civil-defense", name_ar: "خدمات الدفاع المدني والسلامة", name_en: "Civil Defense & Safety Services", icon: "ShieldAlert", order: 40 },
  { id: "zatca", name_ar: "خدمات الزكاة والضريبة والجمارك", name_en: "ZATCA Tax & Customs Services", icon: "Coins", order: 50 },
  { id: "gosi", name_ar: "خدمات التأمينات الاجتماعية", name_en: "GOSI Social Insurance Services", icon: "FileText", order: 60 },
  { id: "absher-passports", name_ar: "خدمات أبشر والجوازات", name_en: "Absher & Passports Services", icon: "UserCheck", order: 70 },
  { id: "mofa-visas", name_ar: "خدمات وزارة الخارجية والتأشيرات", name_en: "MOFA & Visa Services", icon: "Globe", order: 80 },
  { id: "najiz-justice", name_ar: "خدمات ناجز ووزارة العدل", name_en: "Najiz & Ministry of Justice Services", icon: "Scale", order: 90 },
  { id: "contracts-ops", name_ar: "خدمات المنشآت والعقود", name_en: "Establishment Services & Rental Contracts", icon: "Home", order: 100 },
  { id: "modon", name_ar: "خدمات منصة مدن", name_en: "MODON Platform Services", icon: "HardHat", order: 110 },
  { id: "chamber", name_ar: "خدمات الغرفة التجارية", name_en: "Chamber of Commerce Services", icon: "Award", order: 120 },
  { id: "transportation", name_ar: "خدمات النقل", name_en: "Transport Authority Services", icon: "Truck", order: 130 },
  { id: "health-insurance", name_ar: "خدمات التأمين الصحي", name_en: "Health Insurance Services", icon: "HeartPulse", order: 140 },
  { id: "traffic-vehicles", name_ar: "خدمات المركبات والمرور", name_en: "Traffic & Vehicle Services", icon: "Car", order: 150 },
  { id: "investment-biz", name_ar: "خدمات الاستثمار والأعمال", name_en: "Business Investment Services", icon: "TrendingUp", order: 160 }
];

// Mapping structure for existing services to new category IDs
const categoryMapping = {
  "qiwa": "hr-qiwa",
  "human-resources": "hr-qiwa",
  "business-center": "commerce-business",
  "municipality": "municipality-balady",
  "absher": "absher-passports",
  "najiz": "najiz-justice",
  "ejar": "contracts-ops"
};

// Detailed service items catalog to seed
const servicesToSeed = [
  // 1. HR & Qiwa
  { id: "qiwa-open-account", title_ar: "فتح وتفعيل حساب المنشأة", title_en: "Open and Activate Facility Account", category_id: "hr-qiwa", desc_ar: "فتح حساب منشأة جديد وتفعيله عبر الموارد البشرية ومنصة قوى.", desc_en: "Open new facility account and activate it via Qiwa and HR systems.", docs_ar: "السجل التجاري للمنشأة، الهوية الوطنية للمالك", docs_en: "Commercial Register, National ID of Owner", completion: "1-2 أيام عمل" },
  { id: "qiwa-manage-file", title_ar: "إدارة ملف المنشأة", title_en: "Manage Facility Profile", category_id: "hr-qiwa", desc_ar: "تحديث وإدارة بيانات ومستخدمي وصلاحيات ملف المنشأة.", desc_en: "Update and manage profile details, users, and permissions of the facility.", docs_ar: "السجل التجاري، تفويض رسمي للممثل", docs_en: "Commercial Register, Official delegation document", completion: "يوم عمل واحد" },
  { id: "qiwa-issue-permits", title_ar: "إصدار رخص العمل", title_en: "Issue Work Permits", category_id: "hr-qiwa", desc_ar: "تقديم طلبات إصدار رخص العمل وتسهيل معاملات العمالة.", desc_en: "Submit requests to issue work permits for employees.", docs_ar: "بيانات الإقامة للموظف، رقم الحدود", docs_en: "Employee residence data or Border Number", completion: "فوري" },
  { id: "qiwa-renew-permits", title_ar: "تجديد رخص العمل", title_en: "Renew Work Permits", category_id: "hr-qiwa", desc_ar: "تجديد صلاحية رخص العمل وتحديث البيانات في قوى ومكتب العمل.", desc_en: "Renew validity of work permits and update records in Qiwa.", docs_ar: "بيانات رخصة العمل القديمة والإقامة", docs_en: "Old work permit and Residence ID details", completion: "فوري" },
  { id: "qiwa-transfer-sponsorship", title_ar: "نقل خدمات العمالة", title_en: "Transfer Employee Sponsorship", category_id: "hr-qiwa", desc_ar: "تعديل ونقل خدمات الموظفين والعمالة الوافدة بين المنشآت إلكترونياً.", desc_en: "Modify and transfer employee sponsorship between establishments.", docs_ar: "موافقة صاحب العمل الحالي، بيانات المنشأة الجديدة", docs_en: "Current employer consent, new facility details", completion: "1-3 أيام عمل" },
  { id: "qiwa-change-professions", title_ar: "تغيير المهن", title_en: "Modify Profession", category_id: "hr-qiwa", desc_ar: "تعديل وتحديث المهنة الوظيفية للموظف في التأمينات ومكتب العمل.", desc_en: "Modify and update employee's official profession designation.", docs_ar: "شهادة علمية مصدقة، تفويض المنشأة", docs_en: "Certified educational certificate, company authorization", completion: "1-3 أيام عمل" },
  { id: "qiwa-issue-contracts", title_ar: "إصدار عقود العمل", title_en: "Create Employment Contract", category_id: "hr-qiwa", desc_ar: "إنشاء عقود وظيفية موثقة إلكترونياً ومتوافقة مع نظام مكتب العمل.", desc_en: "Create certified digital employment contracts compliant with Ministry rules.", docs_ar: "الهوية الوطنية أو الإقامة للموظف، تفاصيل الراتب والمهام", docs_en: "National ID or Residence of employee, salary details", completion: "يوم عمل واحد" },
  { id: "qiwa-renew-contracts", title_ar: "تجديد عقود العمل", title_en: "Renew Employment Contracts", category_id: "hr-qiwa", desc_ar: "تجديد وتمديد عقود العمل الرسمية والموثقة للموظفين.", desc_en: "Renew and extend valid certified employment contracts for employees.", docs_ar: "رقم العقد الحالي، التعديلات المقترحة", docs_en: "Current contract number, proposed updates", completion: "يوم عمل واحد" },
  { id: "qiwa-manage-contracts", title_ar: "إدارة وتوثيق العقود", title_en: "Manage and Certify Contracts", category_id: "hr-qiwa", desc_ar: "توثيق واعتماد عقود العمل إلكترونياً عبر منصة قوى.", desc_en: "Certify and approve employment agreements digitally on Qiwa.", docs_ar: "بيانات العقد المعتمد، موافقة الموظف", docs_en: "Approved contract details, employee consent", completion: "يوم عمل واحد" },
  { id: "qiwa-saudization-nitaqat", title_ar: "خدمات التوطين ونطاقات", title_en: "Saudization & Nitaqat Services", category_id: "hr-qiwa", desc_ar: "تحسين نسبة التوطين ومتابعة درجات النطاق الأخضر للمنشآت.", desc_en: "Improve Saudization rates and monitor facility's Nitaqat tier.", docs_ar: "كشف العمالة الحالي، شهادة السعودة", docs_en: "Current workforce roster, Saudization cert", completion: "1-2 أيام عمل" },
  { id: "qiwa-saudization-inquire", title_ar: "الاستعلام عن نسب التوطين", title_en: "Inquire Saudization Rates", category_id: "hr-qiwa", desc_ar: "الاستعلام ودراسة نسب السعودة المطلوبة والشرطية للمنشأة.", desc_en: "Inquire and analyze required Saudization targets for the facility.", docs_ar: "رقم المنشأة الموحد", docs_en: "Unified facility registration number", completion: "فوري" },
  { id: "qiwa-violations", title_ar: "معالجة ملاحظات ومخالفات المنشأة", title_en: "Resolve Facility Violations", category_id: "hr-qiwa", desc_ar: "الاعتراض وحل وتسوية المخالفات المفروضة على المنشأة من مكتب العمل.", desc_en: "Object and resolve penalties imposed on the facility by Ministry of Labor.", docs_ar: "مستند المخالفة، إثباتات التسوية أو الدفع", docs_en: "Violation document, proof of settlement or payment", completion: "2-4 أيام عمل" },
  { id: "qiwa-saudization-cert", title_ar: "خدمات السعودة والتوطين", title_en: "Saudization Certificates", category_id: "hr-qiwa", desc_ar: "إصدار شهادة السعودة الرسمية المعتمدة للمؤسسات.", desc_en: "Issue official Saudization certificate for commercial companies.", docs_ar: "رقم السجل التجاري والاشتراكات المعتمدة", docs_en: "Commercial Registration and certified subscriptions", completion: "يوم عمل واحد" },
  { id: "qiwa-professional-visas", title_ar: "التأشيرات المهنية", title_en: "Professional Work Visas", category_id: "hr-qiwa", desc_ar: "إصدار تأشيرات العمل المهنية الفورية للشركات والمؤسسات.", desc_en: "Issue instant professional work visas for companies and enterprises.", docs_ar: "موافقة وزارة العمل، السجل التجاري", docs_en: "Ministry approval, Commercial Registration", completion: "1-2 أيام عمل" },
  { id: "qiwa-recruitment-req", title_ar: "طلبات الاستقدام", title_en: "Recruitment Requests", category_id: "hr-qiwa", desc_ar: "إدارة وتقديم طلبات تأشيرات استقدام العمالة للمؤسسات.", desc_en: "Manage and submit recruitment visa requests for organizations.", docs_ar: "موافقة الجهة الحكومية، السجل التجاري", docs_en: "Government consent, Commercial Registration", completion: "2-3 أيام عمل" },
  { id: "qiwa-domestic-workers", title_ar: "خدمات العمالة المنزلية حسب المنصة المختصة", title_en: "Domestic Workers Services", category_id: "hr-qiwa", desc_ar: "إصدار وتجديد وإلغاء تأشيرات العمالة المنزلية عبر مساند أو منصة أبشر.", desc_en: "Issue, renew and cancel domestic worker visas via Musaned or Absher.", docs_ar: "الهوية الوطنية، إثبات الملاءة المالية للمستفيد", docs_en: "National ID, financial solvency proof of applicant", completion: "1-2 أيام عمل" },
  { id: "qiwa-labor-office", title_ar: "خدمات مكتب العمل", title_en: "Labor Office Services", category_id: "hr-qiwa", desc_ar: "إدارة فتح وتحديث الملفات وتنزيل وحساب نسب مكتب العمل.", desc_en: "Manage opening, updating profiles and calculating Ministry of Labor dues.", docs_ar: "السجل التجاري والترخيص البلدي", docs_en: "Commercial Registration and Municipal License", completion: "1-2 أيام عمل" },
  { id: "qiwa-manage-locations", title_ar: "إدارة مواقع المنشأة", title_en: "Manage Facility Locations", category_id: "hr-qiwa", desc_ar: "تحديث وإضافة العناوين والمواقع الرسمية للمؤسسة في منصة قوى.", desc_en: "Update and add official addresses and locations of the facility.", docs_ar: "العنوان الوطني للمنشأة", docs_en: "National Address of the establishment", completion: "فوري" },

  // 2. Commerce & Business Center
  { id: "commerce-issue-cr", title_ar: "إصدار سجل تجاري", title_en: "Issue Commercial Register (CR)", category_id: "commerce-business", desc_ar: "تأسيس وإصدار السجل التجاري الفوري للمؤسسات والشركات.", desc_en: "Establish and issue instant Commercial Register for companies.", docs_ar: "رقم الهوية للمالك، حجز الاسم التجاري", docs_en: "Owner ID number, reserved trade name", completion: "يوم عمل واحد" },
  { id: "commerce-edit-cr", title_ar: "تعديل السجل التجاري", title_en: "Modify Commercial Register (CR)", category_id: "commerce-business", desc_ar: "تعديل وتحديث بيانات السجل التجاري (رأس المال، الشركاء، العنوان).", desc_en: "Update Commercial Register details (capital, partners, address).", docs_ar: "رقم السجل التجاري، تفاصيل التعديلات المطلوبة", docs_en: "Commercial Register Number, requested modifications", completion: "1-2 أيام عمل" },
  { id: "commerce-renew-cr", title_ar: "تجديد السجل التجاري", title_en: "Renew Commercial Register (CR)", category_id: "commerce-business", desc_ar: "تجديد صلاحية السجل التجاري إلكترونياً لضمان سريانه.", desc_en: "Renew commercial registration online to ensure compliance.", docs_ar: "رقم السجل التجاري المطلوب تجديده", docs_en: "Commercial Register Number to renew", completion: "فوري" },
  { id: "commerce-cancel-cr", title_ar: "شطب سجل تجاري", title_en: "Cancel Commercial Register (CR)", category_id: "commerce-business", desc_ar: "إلغاء وشطب السجلات التجارية وتصفية المنشأة بصورة رسمية.", desc_en: "Delete and cancel commercial registers and dissolve the business.", docs_ar: "رقم السجل التجاري، تسوية مستحقات البلدية والغرفة", docs_en: "Commercial Register, settlement of municipal and chamber dues", completion: "1-2 أيام عمل" },
  { id: "commerce-add-activities", title_ar: "إضافة الأنشطة", title_en: "Add Business Activities", category_id: "commerce-business", desc_ar: "إضافة أنشطة تجارية جديدة للسجل التجاري القائم.", desc_en: "Add new business activities to the existing Commercial Register.", docs_ar: "رقم السجل التجاري، اختيار الأنشطة المطلوبة", docs_en: "Commercial Register, selected activities list", completion: "يوم عمل واحد" },
  { id: "commerce-remove-activities", title_ar: "حذف الأنشطة", title_en: "Remove Business Activities", category_id: "commerce-business", desc_ar: "حذف أو إلغاء أنشطة تجارية من السجل التجاري القائم.", desc_en: "Delete or cancel business activities from the existing Commercial Register.", docs_ar: "رقم السجل التجاري، تحديد الأنشطة المراد حذفها", docs_en: "Commercial Register, list of activities to remove", completion: "يوم عمل واحد" },
  { id: "commerce-reserve-name", title_ar: "حجز الاسم التجاري", title_en: "Reserve Trade Name", category_id: "commerce-business", desc_ar: "حجز اسم تجاري مميز وحصري للمنشأة عبر وزارة التجارة.", desc_en: "Reserve a distinct and exclusive trade name for the company.", docs_ar: "الاسم المقترح، الهوية الوطنية للمستفيد", docs_en: "Proposed name, National ID of applicant", completion: "فوري" },
  { id: "commerce-issue-corp", title_ar: "إصدار وتعديل بيانات المؤسسة", title_en: "Issue and Edit Entity Profile", category_id: "commerce-business", desc_ar: "إنشاء أو تحديث ملف الكيان القانوني للمؤسسة.", desc_en: "Establish or update the legal entity profile of the enterprise.", docs_ar: "السجل التجاري، الهوية الوطنية للمالك", docs_en: "Commercial Register, Owner National ID", completion: "1-2 أيام عمل" },
  { id: "commerce-transfer-cr", title_ar: "نقل ملكية السجل التجاري", title_en: "Transfer Ownership of CR", category_id: "commerce-business", desc_ar: "نقل ملكية وتنازل السجل التجاري من شخص لآخر بصورة قانونية.", desc_en: "Transfer commercial register ownership to another person legally.", docs_ar: "عقد التنازل الإلكتروني، الهوية الوطنية للمشتري والبائع", docs_en: "Electronic assignment deed, Buyer & Seller IDs", completion: "2-3 أيام عمل" },
  { id: "commerce-beneficiary", title_ar: "إدارة المستفيد الحقيقي", title_en: "Manage Ultimate Beneficial Owner (UBO)", category_id: "commerce-business", desc_ar: "تسجيل والإفصاح عن بيانات المستفيد الحقيقي للمنشآت والشركات.", desc_en: "Register and disclose Ultimate Beneficial Owner data for entities.", docs_ar: "السجل التجاري، الهوية الوطنية للمالكين الحقيقيين", docs_en: "Commercial Register, National IDs of actual beneficiaries", completion: "يوم عمل واحد" },
  { id: "commerce-disclosure", title_ar: "الإفصاح والبيانات التجارية", title_en: "Commercial Disclosure & Data", category_id: "commerce-business", desc_ar: "تقديم إقرارات الإفصاح المالي والبيانات التجارية السنوية.", desc_en: "Submit financial disclosures and commercial statements annually.", docs_ar: "القوائم المالية السنوية للمنشأة", docs_en: "Annual financial statements of the facility", completion: "2-3 أيام عمل" },
  { id: "commerce-trade-names", title_ar: "خدمات الأسماء التجارية", title_en: "Trade Name Services", category_id: "commerce-business", desc_ar: "الاستعلام وتحديث وتعديل الأسماء التجارية المحجوزة والقائمة.", desc_en: "Inquire, update, and modify existing or reserved trade names.", docs_ar: "رقم حجز الاسم أو رقم السجل التجاري", docs_en: "Trade name reservation code or Commercial Register", completion: "يوم عمل واحد" },
  { id: "commerce-trademarks", title_ar: "خدمات العلامات التجارية", title_en: "Trademark Services", category_id: "commerce-business", desc_ar: "تسجيل وحماية العلامات التجارية والشعارات إلكترونياً.", desc_en: "Register and protect commercial trademarks and logos online.", docs_ar: "صورة العلامة التجارية، تفاصيل النشاط والمالك", docs_en: "Image of trademark, activity and owner details", completion: "3-5 أيام عمل" },
  { id: "commerce-cr-docs", title_ar: "استخراج وطباعة مستندات السجل", title_en: "Extract and Print CR Documents", category_id: "commerce-business", desc_ar: "استخراج شهادات ومستندات السجل التجاري المعتمدة إلكترونياً.", desc_en: "Extract certified commercial registration documents online.", docs_ar: "رقم السجل التجاري للمنشأة", docs_en: "Commercial Register Number of the facility", completion: "فوري" },
  { id: "commerce-annual-confirm", title_ar: "التأكيد السنوي لبيانات السجل التجاري", title_en: "Annual Confirmation of CR Data", category_id: "commerce-business", desc_ar: "إجراء التأكيد السنوي الإلزامي لبيانات السجل التجاري عبر المركز السعودي للأعمال.", desc_en: "Complete mandatory annual validation of Commercial Register data via SBC.", docs_ar: "رقم السجل التجاري، الهوية الوطنية للمدير", docs_en: "Commercial Register, Manager National ID", completion: "يوم عمل واحد" },

  // 3. Municipal & Balady
  { id: "muni-issue-license", title_ar: "إصدار الرخصة البلدية", title_en: "Issue Municipal License", category_id: "municipality-balady", desc_ar: "إصدار رخصة بلدية فورية جديدة للنشاط التجاري والمحلات.", desc_en: "Issue new instant municipal license for commercial activities.", docs_ar: "عقد الإيجار الإلكتروني، مخطط السلامة، العنوان الوطني", docs_en: "Ejar contract, safety layout, National Address", completion: "2-3 أيام عمل" },
  { id: "muni-renew-license", title_ar: "تجديد الرخص", title_en: "Renew Municipal Licenses", category_id: "municipality-balady", desc_ar: "تجديد صلاحية الرخصة البلدية للمنشأة وتحديث بياناتها.", desc_en: "Renew validity of facility municipal licenses and update profile.", docs_ar: "رقم الرخصة البلدية المراد تجديدها، عقد الإيجار الساري", docs_en: "Municipal License Number to renew, active Ejar contract", completion: "يوم عمل واحد" },
  { id: "muni-edit-license", title_ar: "تعديل الرخصة", title_en: "Modify Municipal License", category_id: "municipality-balady", desc_ar: "تعديل بيانات أو مساحة أو فئة الرخصة البلدية القائمة.", desc_en: "Modify details, area, or category of the existing municipal license.", docs_ar: "رقم الرخصة، المستندات الداعمة للتعديل", docs_en: "License Number, supporting update documents", completion: "1-2 أيام عمل" },
  { id: "muni-transfer-license", title_ar: "نقل ملكية الرخصة", title_en: "Transfer License Ownership", category_id: "municipality-balady", desc_ar: "نقل ملكية الرخصة البلدية للمنشأة للمستفيد الجديد.", desc_en: "Transfer municipal license ownership of the facility to the new user.", docs_ar: "السجل التجاري الجديد، تنازل المالك السابق", docs_en: "New Commercial Register, former owner assignment", completion: "2-3 أيام عمل" },
  { id: "muni-change-activity", title_ar: "تغيير النشاط", title_en: "Change Municipal Activity", category_id: "municipality-balady", desc_ar: "تعديل وتغيير النشاط التجاري للرخصة البلدية القائمة.", desc_en: "Modify and change the commercial activity of the municipal license.", docs_ar: "رقم الرخصة، السجل التجاري المحدث بالنشاط الجديد", docs_en: "License number, updated Commercial Register", completion: "1-2 أيام عمل" },
  { id: "muni-add-activity", title_ar: "إضافة نشاط", title_en: "Add Municipal Activity", category_id: "municipality-balady", desc_ar: "إضافة نشاط تجاري إضافي أو فرعي للرخصة البلدية.", desc_en: "Add additional or branch activity to the municipal license.", docs_ar: "رقم الرخصة، تفاصيل النشاط الجديد", docs_en: "License number, new activity details", completion: "يوم عمل واحد" },
  { id: "muni-issue-health", title_ar: "إصدار الشهادات الصحية", title_en: "Issue Health Certificates", category_id: "municipality-balady", desc_ar: "إصدار شهادات صحية للعاملين في الأنشطة ذات العلاقة بالصحة العامة.", desc_en: "Issue health certificates for employees in health-related sectors.", docs_ar: "الفحص الطبي الساري، الهوية الوطنية أو الإقامة للعامل", docs_en: "Valid medical check, National ID or Residence of worker", completion: "1-2 أيام عمل" },
  { id: "muni-renew-health", title_ar: "تجديد الشهادات الصحية للعاملين", title_en: "Renew Health Certificates", category_id: "municipality-balady", desc_ar: "تجديد الشهادة الصحية للعامل بعد إجراء الفحص الطبي المعتمد.", desc_en: "Renew employee health certificate after medical exam verification.", docs_ar: "رقم الشهادة القديمة، الفحص الطبي الجديد", docs_en: "Old certificate number, new medical check", completion: "يوم عمل واحد" },
  { id: "muni-sign-permit", title_ar: "تصاريح اللوحات", title_en: "Signboard Permits", category_id: "municipality-balady", desc_ar: "إصدار تصاريح لوحات المحلات التجارية الإعلانية والتعريفية.", desc_en: "Issue billboard or signboard permits for retail establishments.", docs_ar: "مقاسات اللوحة، صورة توضيحية لواجهة المحل", docs_en: "Signboard dimensions, retail storefront photo", completion: "1-2 أيام عمل" },
  { id: "muni-ads-permit", title_ar: "تصاريح الإعلانات", title_en: "Advertising Permits", category_id: "municipality-balady", desc_ar: "إصدار التراخيص اللازمة للحملات الإعلانية الخارجية والترويجية.", desc_en: "Issue required permits for outdoor advertisement campaigns.", docs_ar: "تفاصيل الإعلان والجهة المستفيدة", docs_en: "Ad copy details, beneficiary identification", completion: "2-3 أيام عمل" },
  { id: "muni-sidewalk-permit", title_ar: "تصاريح إشغال الأرصفة", title_en: "Sidewalk Occupancy Permits", category_id: "municipality-balady", desc_ar: "إصدار تصريح إشغال الرصيف للمحلات التجارية والمطاعم بشكل نظامي.", desc_en: "Issue official sidewalk occupancy permit for cafes and shops.", docs_ar: "كروكي الموقع، الرخصة البلدية السارية", docs_en: "Site layout sketch, valid municipal license", completion: "2-3 أيام عمل" },
  { id: "muni-events-permit", title_ar: "تصاريح الفعاليات", title_en: "Events Permits", category_id: "municipality-balady", desc_ar: "إصدار تصاريح بلدية مؤقتة للفعاليات والأنشطة العامة.", desc_en: "Issue temporary municipal permits for public events.", docs_ar: "موافقة هيئة الترفيه أو الجهة المعنية، كروكي الفعالية", docs_en: "Entertainment Authority approval, event layout plan", completion: "2-4 أيام عمل" },
  { id: "muni-commercial-locations", title_ar: "خدمات المواقع والأنشطة التجارية", title_en: "Commercial Site Services", category_id: "municipality-balady", desc_ar: "الاستعلام وتجهيز المواقع الجغرافية ومطابقة أنشطة المحلات.", desc_en: "Inquire and verify geographical coordinates for store activities.", docs_ar: "الإحداثيات الجغرافية للموقع، صك الملكية أو العقد", docs_en: "Geographical coordinates, deed or rent contract", completion: "2-3 أيام عمل" },
  { id: "muni-compliance", title_ar: "متابعة اشتراطات النشاط", title_en: "Monitor Activity Requirements", category_id: "municipality-balady", desc_ar: "متابعة وتحديث الاشتراطات الفنية المعتمدة للنشاط البلدي.", desc_en: "Monitor and update certified technical requirements of municipal activities.", docs_ar: "كود النشاط البلدي للمحل", docs_en: "Municipal activity code of the shop", completion: "يوم عمل واحد" },
  { id: "muni-resolve-notes", title_ar: "معالجة الملاحظات والطلبات", title_en: "Resolve Municipal Inquiries & Demands", category_id: "municipality-balady", desc_ar: "معالجة ومتابعة الطلبات الموقوفة أو الملاحظات الفنية في بلدي.", desc_en: "Address and process suspended municipal requests and technical feedback.", docs_ar: "رقم الطلب البلدي، تفاصيل الملاحظة الفنية", docs_en: "Municipal request number, technical feedback details", completion: "2-3 أيام عمل" },

  // 4. Civil Defense & Safety
  { id: "safety-issue-permit", title_ar: "إصدار رخصة السلامة", title_en: "Issue Safety License", category_id: "civil-defense", desc_ar: "إصدار رخصة الدفاع المدني والسلامة للمحلات والمستودعات.", desc_en: "Issue Civil Defense safety license for retail shops and warehouses.", docs_ar: "تقرير فني من مكتب هندسي معتمد، فاتورة أدوات السلامة", docs_en: "Technical report from certified engineering firm, safety equipment invoice", completion: "2-3 أيام عمل" },
  { id: "safety-requirements", title_ar: "متطلبات السلامة للمنشآت", title_en: "Facility Safety Requirements", category_id: "civil-defense", desc_ar: "تجهيز ودراسة وتوفير الاشتراطات الفنية للدفاع المدني.", desc_en: "Prepare, study, and execute technical specifications of Civil Defense.", docs_ar: "كروكي المحل، نوع النشاط التجاري", docs_en: "Store layout sketch, commercial activity type", completion: "2-3 أيام عمل" },
  { id: "safety-track-requests", title_ar: "متابعة طلبات السلامة", title_en: "Track Safety Requests", category_id: "civil-defense", desc_ar: "متابعة الطلبات المرفوعة في بوابة سلامة للدفاع المدني.", desc_en: "Follow up on requests submitted in the Salamah Civil Defense portal.", docs_ar: "رقم طلب بوابة سلامة", docs_en: "Salamah portal request code", completion: "يوم عمل واحد" },
  { id: "safety-tech-reports", title_ar: "التقارير الفنية المتعلقة بالسلامة", title_en: "Safety Technical Reports", category_id: "civil-defense", desc_ar: "إصدار التقارير الفنية المعتمدة لأجهزة ومخارج السلامة للمحلات.", desc_en: "Issue certified technical reports for safety systems and exits.", docs_ar: "زيارة معاينة ميدانية للموقع", docs_en: "Field inspection visit details", completion: "1-2 أيام عمل" },
  { id: "safety-equipment-setup", title_ar: "تجهيز متطلبات السلامة", title_en: "Prepare Safety Requirements", category_id: "civil-defense", desc_ar: "المساعدة في تجهيز وتوفير طفايات الحريق وصناديق الإسعاف واللوحات الإرشادية للمحلات.", desc_en: "Assistance in providing fire extinguishers, first aid kits, and signs.", docs_ar: "قائمة أدوات السلامة المطلوبة بحسب المساحة والنشاط", docs_en: "Required safety tools list based on area and activity", completion: "2-3 أيام عمل" },
  { id: "safety-docs-setup", title_ar: "تجهيز المستندات", title_en: "Prepare Safety Documents", category_id: "civil-defense", desc_ar: "إعداد وتجهيز مستندات وعقود الصيانة المعتمدة للسلامة.", desc_en: "Compile and prepare certified maintenance contracts for safety.", docs_ar: "رقم السجل التجاري، رخصة البلدية", docs_en: "Commercial Register, Municipal License", completion: "يوم عمل واحد" },
  { id: "safety-inspections", title_ar: "متابعة الزيارات والمعاينات", title_en: "Follow Up on Inspections", category_id: "civil-defense", desc_ar: "تنسيق ومتابعة مواعيد زيارات مفتشي الدفاع المدني للموقع.", desc_en: "Coordinate and follow up on Civil Defense field inspection schedules.", docs_ar: "عنوان المنشأة ورقم الاتصال للمسؤول عن الموقع", docs_en: "Facility address and site manager contact info", completion: "2-3 أيام عمل" },
  { id: "safety-resolve-notes", title_ar: "معالجة الملاحظات", title_en: "Resolve Safety Remarks", category_id: "civil-defense", desc_ar: "حل ومعالجة الملاحظات الفنية المسجلة من قبل الدفاع المدني.", desc_en: "Address and resolve technical notes registered by Civil Defense inspectors.", docs_ar: "نسخة من محضر ملاحظات الدفاع المدني", docs_en: "Copy of Civil Defense inspection remark report", completion: "2-3 أيام عمل" },

  // 5. ZATCA Tax & Customs
  { id: "zatca-register-zakat", title_ar: "التسجيل في الزكاة", title_en: "Register in Zakat", category_id: "zatca", desc_ar: "فتح ملف المنشأة والتسجيل لدى الهيئة العامة للزكاة والضريبة والجمارك.", desc_en: "Create profile and register in ZATCA for zakat filings.", docs_ar: "السجل التجاري، عقد التأسيس، العنوان الوطني", docs_en: "Commercial Register, Articles of Assoc, National Address", completion: "1-2 أيام عمل" },
  { id: "zatca-register-vat", title_ar: "التسجيل في ضريبة القيمة المضافة", title_en: "Register in VAT", category_id: "zatca", desc_ar: "التسجيل الإلزامى أو الاختياري في ضريبة القيمة المضافة (VAT).", desc_en: "Mandatory or voluntary registration in Value Added Tax (VAT).", docs_ar: "السجل التجاري، مستند يوضح المبيعات السنوية المتوقعة أو الفعلية", docs_en: "Commercial Register, statement showing annual sales figures", completion: "1-2 أيام عمل" },
  { id: "zatca-update-profile", title_ar: "تعديل بيانات المنشأة", title_en: "Modify ZATCA Profile Data", category_id: "zatca", desc_ar: "تحديث وتعديل البيانات القانونية للمنشأة في هيئة الزكاة.", desc_en: "Update and modify legal profile details of the facility at ZATCA.", docs_ar: "السجل التجاري المعدل، الهوية الوطنية للمدير", docs_en: "Modified Commercial Register, Manager National ID", completion: "يوم عمل واحد" },
  { id: "zatca-vat-returns", title_ar: "تقديم الإقرارات الضريبية", title_en: "Submit VAT Returns", category_id: "zatca", desc_ar: "إعداد وتقديم الإقرارات الدورية لضريبة القيمة المضافة بشكل نظامي.", desc_en: "Prepare and submit periodic VAT return filings in compliance with ZATCA.", docs_ar: "كشوفات فواتير المبيعات والمشتريات خلال الفترة الضريبية", docs_en: "Sales and purchases invoices reports for the tax period", completion: "1-3 أيام عمل" },
  { id: "zatca-zakat-returns", title_ar: "تقديم الإقرارات الزكوية", title_en: "Submit Zakat Returns", category_id: "zatca", desc_ar: "إعداد وتقديم الإقرارات الزكوية السنوية للمؤسسات والشركات.", desc_en: "Prepare and submit annual zakat return filings for entities.", docs_ar: "الحسابات الختامية السنوية، كشف الأرباح والخسائر للمنشأة", docs_en: "Annual financial accounts, profit and loss report of the facility", completion: "2-4 أيام عمل" },
  { id: "zatca-certificates", title_ar: "الشهادات الزكوية والضريبية", title_en: "Zakat & Tax Certificates", category_id: "zatca", desc_ar: "إصدار واستخراج شهادة الزكاة والضريبة والجمارك الرسمية السارية.", desc_en: "Issue and extract official active Zakat and Tax certificates.", docs_ar: "سداد المستحقات والالتزامات للضريبة أو الزكاة", docs_en: "Settlement of tax or zakat obligations", completion: "يوم عمل واحد" },
  { id: "zatca-e-invoicing", title_ar: "الفوترة الإلكترونية", title_en: "Electronic Invoicing (Fatoora)", category_id: "zatca", desc_ar: "المساعدة في إعداد وتطبيق نظام الفوترة الإلكترونية (فاتورة) للمنشآت.", desc_en: "Assistance in setting up and implementing ZATCA Electronic Invoicing.", docs_ar: "بيانات نظام المحاسبة والفوترة المستخدم", docs_en: "Details of accounting and invoicing software used", completion: "2-3 أيام عمل" },
  { id: "zatca-tin-number", title_ar: "الرقم المميز", title_en: "Get Tax Identification Number (TIN)", category_id: "zatca", desc_ar: "إصدار واستخراج الرقم المميز (TIN) الضريبي للمنشآت.", desc_en: "Issue and extract Tax Identification Number (TIN) for enterprises.", docs_ar: "السجل التجاري، عقد التأسيس للمنشأة", docs_en: "Commercial Register, Articles of Association", completion: "فوري" },
  { id: "zatca-corporate-services", title_ar: "خدمات المنشآت لدى هيئة الزكاة والضريبة والجمارك", title_en: "ZATCA Corporate Services", category_id: "zatca", desc_ar: "متابعة وإدارة ملفات المنشآت الكبرى والمتوسطة وتطبيقات الجمارك.", desc_en: "Follow up and manage big and medium facility profiles at ZATCA.", docs_ar: "التفويض الرسمي، رقم المنشأة الموحد", docs_en: "Official authorization, unified facility number", completion: "1-2 أيام عمل" },
  { id: "zatca-claims", title_ar: "متابعة المطالبات", title_en: "Follow Up on Tax Claims", category_id: "zatca", desc_ar: "متابعة المطالبات والاستردادات الضريبية والمالية مع هيئة الزكاة.", desc_en: "Follow up on tax claims, refunds, and financial queries with ZATCA.", docs_ar: "مستندات وتفاصيل الفواتير والمدفوعات الزائدة", docs_en: "Invoices and documents showing surplus payments", completion: "2-4 أيام عمل" },
  { id: "zatca-penalties", title_ar: "متابعة المخالفات", title_en: "Follow Up on Tax Violations", category_id: "zatca", desc_ar: "مراجعة وتسوية المخالفات الضريبية أو الغرامات غير المسددة.", desc_en: "Review and settle tax violations or unpaid penalty charges.", docs_ar: "رقم إشعار المخالفة أو الغرامة، السجل التجاري", docs_en: "Violation notice number, Commercial Register", completion: "1-2 أيام عمل" },
  { id: "zatca-objections", title_ar: "الاعتراضات والتسويات عندما تكون خدمة متاحة ومناسبة", title_en: "Objections & Settle Disputes", category_id: "zatca", desc_ar: "إعداد وتقديم طلبات الاعتراض على قرارات الربط الزكوي أو الضريبي.", desc_en: "Prepare and submit objection requests against ZATCA tax decisions.", docs_ar: "قرار الربط الصادر، مذكرة الدفوع القانونية والمحاسبية", docs_en: "ZATCA assessment letter, legal and accounting defense statement", completion: "3-5 أيام عمل" },

  // 6. GOSI
  { id: "gosi-register-company", title_ar: "تسجيل المنشأة", title_en: "Register Establishment in GOSI", category_id: "gosi", desc_ar: "فتح وتفعيل ملف اشتراك للمنشأة لدى المؤسسة العامة للتأمينات الاجتماعية.", desc_en: "Open and activate insurance subscription file for entity in GOSI.", docs_ar: "السجل التجاري، تفاصيل العنوان الوطني", docs_en: "Commercial Register, National Address details", completion: "يوم عمل واحد" },
  { id: "gosi-add-employee", title_ar: "إضافة المشتركين", title_en: "Add Subscribers (Employees)", category_id: "gosi", desc_ar: "إضافة وتسجيل الموظفين السعوديين والوافدين في ملف التأمينات الاجتماعية.", desc_en: "Register Saudi and foreign workers under the establishment's GOSI file.", docs_ar: "الهوية الوطنية أو الإقامة، تاريخ الالتحاق بالعمل، الراتب الأساسي", docs_en: "National ID or Residence, hiring date, basic salary", completion: "فوري" },
  { id: "gosi-remove-employee", title_ar: "استبعاد المشتركين", title_en: "Exclude Subscribers (Terminate)", category_id: "gosi", desc_ar: "استبعاد أو إنهاء اشتراك الموظف في التأمينات عند نهاية الخدمة.", desc_en: "Remove or terminate employee's subscription in GOSI at end of service.", docs_ar: "الهوية الوطنية أو الإقامة، تاريخ انتهاء العلاقة التعاقدية", docs_en: "National ID or Residence, contract termination date", completion: "فوري" },
  { id: "gosi-modify-salaries", title_ar: "تعديل الأجور", title_en: "Modify Employee Wages", category_id: "gosi", desc_ar: "تعديل وتحديث الأجور الشهرية والبدلات للمشتركين للتحديث السنوي.", desc_en: "Update monthly basic wages and allowances of subscribers in GOSI.", docs_ar: "العقد المحدث، تفاصيل الراتب الجديد والبدلات", docs_en: "Updated contract, new salary breakdown", completion: "يوم عمل واحد" },
  { id: "gosi-modify-subscriber", title_ar: "تعديل بيانات المشترك", title_en: "Modify Subscriber Profile Data", category_id: "gosi", desc_ar: "تعديل البيانات الشخصية أو العلمية أو المسمى الوظيفي للمشترك.", desc_en: "Modify personal, academic, or professional details of the subscriber.", docs_ar: "صورة الهوية الوطنية أو الإقامة، إثباتات المؤهلات", docs_en: "National ID or Residence card, qualification proofs", completion: "يوم عمل واحد" },
  { id: "gosi-track-payments", title_ar: "متابعة الاشتراكات", title_en: "Follow Up Subscriptions", category_id: "gosi", desc_ar: "متابعة وتسوية الفواتير الشهرية والمدفوعات والمستحقات للتأمينات.", desc_en: "Follow up on monthly subscription bills, dues, and payments.", docs_ar: "رقم اشتراك المنشأة في التأمينات", docs_en: "GOSI establishment registration number", completion: "فوري" },
  { id: "gosi-certificates", title_ar: "استخراج الشهادات", title_en: "Extract GOSI Certificates", category_id: "gosi", desc_ar: "استخراج شهادة التأمينات الاجتماعية الرسمية والخلو من الغرامات.", desc_en: "Extract official certified GOSI subscription and clearance certificates.", docs_ar: "رقم اشتراك المنشأة", docs_en: "GOSI registration number", completion: "فوري" },
  { id: "gosi-salary-file", title_ar: "ملف الأجور", title_en: "Salary File Services", category_id: "gosi", desc_ar: "المساعدة في رفع وتحديث ملف الأجور الشهري المعتمد للموظفين.", desc_en: "Assistance in uploading and updating monthly salary files.", docs_ar: "ملف الإكسيل المعتمد لبيانات الرواتب والموظفين", docs_en: "Certified Excel template of salary breakdown", completion: "يوم عمل واحد" },
  { id: "gosi-mudad-integration", title_ar: "خدمات مدد المرتبطة بالأجور", title_en: "Mudad Platform Wage Protection", category_id: "gosi", desc_ar: "ربط وإدارة ملف الأجور ونظام حماية الأجور عبر منصة مدد المعتمدة.", desc_en: "Connect and manage wage protection system files via Mudad platform.", docs_ar: "بيانات المنشأة، حساب البنك التجاري المربوط", docs_en: "Facility profile details, linked commercial bank account", completion: "1-2 أيام عمل" },
  { id: "gosi-resolve-requests", title_ar: "معالجة الملاحظات والطلبات", title_en: "Resolve GOSI Remarks & Queries", category_id: "gosi", desc_ar: "حل ومتابعة الاعتراضات والملاحظات المتعلقة بنسب الاشتراك والقرارات.", desc_en: "Resolve GOSI remarks, audits, and objections on subscription rates.", docs_ar: "رقم المعاملة، المستندات الداعمة للمراجعة", docs_en: "Transaction number, supporting check documents", completion: "2-3 أيام عمل" },
  { id: "gosi-manage-users", title_ar: "إدارة مستخدمي المنشأة", title_en: "Manage GOSI Portal Users", category_id: "gosi", desc_ar: "إضافة وتعديل المفوضين والمدراء الممثلين للمنشأة في البوابة.", desc_en: "Add or edit authorized managers representing the facility in GOSI.", docs_ar: "التفويض الرسمي للشركة، رقم الهوية الوطنية للمدير الجديد", docs_en: "Official company authorization, National ID of new manager", completion: "يوم عمل واحد" },

  // 7. Absher & Passports
  { id: "absher-issue-iqama", title_ar: "إصدار الإقامة", title_en: "Issue Iqama", category_id: "absher-passports", desc_ar: "إصدار هوية مقيم جديدة للعمالة الوافدة للمرة الأولى.", desc_en: "Issue new resident identity card (Iqama) for foreign workers.", docs_ar: "رقم الحدود، نتيجة الفحص الطبي، سداد الرسوم والتأمين", docs_en: "Border Number, medical check result, fees & insurance payment", completion: "1-2 أيام عمل" },
  { id: "absher-renew-iqama", title_ar: "تجديد الإقامة", title_en: "Renew Iqama", category_id: "absher-passports", desc_ar: "تجديد صلاحية هوية المقيم (الإقامة) للعمالة لتجنب الغرامات.", desc_en: "Renew residency (Iqama) validity for expatriate employees.", docs_ar: "سداد الرسوم والضمان الاجتماعي الطبي المعتمد، الإقامة الحالية", docs_en: "Payment of fees & medical insurance, current Iqama details", completion: "فوري" },
  { id: "absher-transfer-services", title_ar: "نقل الخدمات حسب الصلاحيات", title_en: "Transfer Residency Services", category_id: "absher-passports", desc_ar: "إكمال معاملات نقل خدمات المقيمين عبر أبشر وتحديث سجل الجوازات.", desc_en: "Complete resident sponsorship transfers via Absher & Passports.", docs_ar: "موافقة الكفيل السابق والمستفيد الجديد، بيانات الإقامة", docs_en: "Consent of former sponsor & new user, Iqama details", completion: "1-2 أيام عمل" },
  { id: "absher-exit-reentry-issue", title_ar: "إصدار تأشيرة خروج وعودة", title_en: "Issue Exit/Re-entry Visa", category_id: "absher-passports", desc_ar: "إصدار تأشيرة الخروج والعودة (مفردة أو متعددة) للمقيمين.", desc_en: "Issue single or multiple exit/re-entry visas for residents.", docs_ar: "سداد رسوم التأشيرة الحكومية، إقامة سارية المفعول للمستفيد", docs_en: "Government visa fee payment, valid Iqama of applicant", completion: "فوري" },
  { id: "absher-exit-reentry-cancel", title_ar: "إلغاء تأشيرة خروج وعودة", title_en: "Cancel Exit/Re-entry Visa", category_id: "absher-passports", desc_ar: "إلغاء تأشيرة خروج وعودة قائمة وغير مستخدمة لتجنب الغرامات.", desc_en: "Cancel active unused exit/re-entry visa to avoid penalty charges.", docs_ar: "رقم الإقامة، تفاصيل التأشيرة الصادرة", docs_en: "Iqama Number, details of issued visa", completion: "فوري" },
  { id: "absher-final-exit-issue", title_ar: "إصدار خروج نهائي", title_en: "Issue Final Exit Visa", category_id: "absher-passports", desc_ar: "إصدار تأشيرة خروج نهائي للمقيمين عند مغادرة المملكة.", desc_en: "Issue final exit visa for residents leaving the Kingdom permanently.", docs_ar: "سجل خلو من المخالفات المرورية، إقامة سارية، جواز سفر ساري", docs_en: "Traffic violation clearance, valid Iqama, valid passport", completion: "فوري" },
  { id: "absher-final-exit-cancel", title_ar: "إلغاء خروج نهائي", title_en: "Cancel Final Exit Visa", category_id: "absher-passports", desc_ar: "إلغاء تأشيرة الخروج النهائي المصدرة للعمالة قبل مغادرة المملكة.", desc_en: "Cancel issued final exit visa before employee leaves the country.", docs_ar: "رقم الإقامة، جواز سفر الموظف ساري المفعول", docs_en: "Iqama Number, valid passport of employee", completion: "فوري" },
  { id: "absher-modify-profession-res", title_ar: "تعديل المهنة حسب الصلاحيات", title_en: "Modify Resident Profession", category_id: "absher-passports", desc_ar: "تعديل المهنة الرسمية للمقيم في هوية مقيم (الإقامة).", desc_en: "Update the official profession title printed on the resident card.", docs_ar: "موافقة وزارة الموارد البشرية، المؤهل العلمي المعتمد", docs_en: "Ministry approval, accredited scientific degree certificate", completion: "1-2 أيام عمل" },
  { id: "absher-residents-services", title_ar: "خدمات المقيمين", title_en: "Resident Services Services", category_id: "absher-passports", desc_ar: "الاستعلام وحل المعاملات والطلبات والملاحظات المرتبطة بالمقيمين.", desc_en: "Inquire and resolve issues, requests, and remarks for residents.", docs_ar: "رقم الإقامة أو جواز السفر للمستفيد", docs_en: "Iqama or Passport Number of the applicant", completion: "1-2 أيام عمل" },
  { id: "absher-dependents", title_ar: "خدمات أفراد الأسرة", title_en: "Family Members Services", category_id: "absher-passports", desc_ar: "إصدار وتجديد وإلغاء إقامات أفراد الأسرة والتابعين للمقيمين.", desc_en: "Issue, renew, and cancel residency IDs of family dependents.", docs_ar: "عقد النكاح أو شهادات الميلاد، الفحص الطبي للتابعين", docs_en: "Marriage certificate or birth certificates, medical check", completion: "1-2 أيام عمل" },
  { id: "absher-inquire-status", title_ar: "الاستعلام عن حالة الإقامة والتأشيرات", title_en: "Inquire Residency & Visas Status", category_id: "absher-passports", desc_ar: "الاستعلام الإلكتروني عن صلاحية وتواريخ انتهاء الإقامات والتأشيرات.", desc_en: "Query validity and expiry dates of residencies and visas online.", docs_ar: "رقم الإقامة أو رقم الحدود للمستعلم عنه", docs_en: "Iqama or Border Number of search target", completion: "فوري" },
  { id: "absher-business-delegation", title_ar: "تفاويض أبشر أعمال", title_en: "Absher Business Delegations", category_id: "absher-passports", desc_ar: "إصدار وتحديث تفاويض الممثلين والمدراء في منصة أبشر أعمال.", desc_en: "Issue and update representative delegations in Absher Business.", docs_ar: "السجل التجاري، الهوية الوطنية للمثل المفوض", docs_en: "Commercial Register, National ID of delegated representative", completion: "فوري" },

  // 8. MOFA & Visas
  { id: "mofa-visit-requests", title_ar: "طلبات الزيارة", title_en: "Visit Visa Requests", category_id: "mofa-visas", desc_ar: "تقديم وتوثيق طلبات الزيارة العائلية أو التجارية عبر الخارجية.", desc_en: "Submit and certify family or business visit visas via MOFA.", docs_ar: "الإقامة للمستضيف، صك القرابة العائلية أو السجل التجاري", docs_en: "Host residency ID, kinship proof or Commercial Register", completion: "2-3 أيام عمل" },
  { id: "mofa-track-visas", title_ar: "متابعة طلبات التأشيرات", title_en: "Track Visa Requests", category_id: "mofa-visas", desc_ar: "متابعة وحل الملاحظات على تأشيرات الزيارة المقدمة للخارجية.", desc_en: "Follow up and resolve remarks on visit visa requests submitted.", docs_ar: "رقم طلب الزيارة بالخارجية", docs_en: "MOFA visit visa request code", completion: "يوم عمل واحد" },
  { id: "mofa-e-delegation", title_ar: "التفويض الإلكتروني", title_en: "Electronic Visa Delegation", category_id: "mofa-visas", desc_ar: "إصدار تفويض إلكتروني على تأشيرات العمل لمكاتب الاستقدام بالخارج.", desc_en: "Issue digital visa delegations for overseas recruitment agencies.", docs_ar: "رقم التأشيرة الصادرة، اسم وكالة الاستقدام المعتمدة", docs_en: "Issued visa code, name of certified recruitment agency", completion: "يوم عمل واحد" },
  { id: "mofa-visa-services", title_ar: "خدمات التأشيرات", title_en: "Visa Services Services", category_id: "mofa-visas", desc_ar: "مراجعة وتحديث معاملات الاستقدام والتأشيرات عبر الخارجية.", desc_en: "Review and update recruitment and visa transactions via MOFA.", docs_ar: "أوراق المعاملة وتفاصيل الطلب بالخارجية", docs_en: "Transaction documents and MOFA request details", completion: "2-3 أيام عمل" },
  { id: "mofa-extend-visit", title_ar: "تمديد الزيارة حسب الحالة", title_en: "Extend Visit Visa", category_id: "mofa-visas", desc_ar: "تقديم طلبات تمديد صلاحية تأشيرة الزيارة العائلية أو التجارية.", desc_en: "Submit requests to extend family or business visit visa validity.", docs_ar: "تأمين طبي ساري للزائر، جواز السفر وتأشيرة الزيارة الحالية", docs_en: "Valid medical insurance for visitor, passport & active visa", completion: "1-2 أيام عمل" },
  { id: "mofa-document-cert", title_ar: "تصديق الوثائق", title_en: "Document Attestation", category_id: "mofa-visas", desc_ar: "تصديق الشهادات والوكالات والعقود من فروع وزارة الخارجية بالمملكة.", desc_en: "Attest educational certificates, POAs, and contracts at MOFA.", docs_ar: "المستند الأصلي المراد تصديقه، الهوية الوطنية للمستفيد", docs_en: "Original document to attest, National ID of applicant", completion: "1-2 أيام عمل" },
  { id: "mofa-track-transactions", title_ar: "متابعة الطلبات والمعاملات", title_en: "Follow Up MOFA Applications", category_id: "mofa-visas", desc_ar: "متابعة إنهاء المعاملات الدبلوماسية والقنصلية لدى الخارجية.", desc_en: "Follow up and finalize consular or diplomatic requests with MOFA.", docs_ar: "رقم المعاملة أو الطلب الإلكتروني الصادر", docs_en: "Transaction number or issued digital request code", completion: "2-3 أيام عمل" },

  // 9. Najiz & Justice
  { id: "najiz-issue-poa", title_ar: "إصدار الوكالات الإلكترونية", title_en: "Issue Electronic POAs", category_id: "najiz-justice", desc_ar: "إصدار وكالة شرعية إلكترونية معتمدة وفورية عبر بوابة ناجز.", desc_en: "Issue certified judicial power of attorney instantly via Najiz.", docs_ar: "الهوية الوطنية للموكل والوكيل، بنود الوكالة المحددة", docs_en: "National IDs of principal and agent, selected POA terms", completion: "فوري" },
  { id: "najiz-cancel-poa", title_ar: "فسخ الوكالة", title_en: "Revoke Power of Attorney", category_id: "najiz-justice", desc_ar: "إلغاء وفسخ الوكالات الشرعية الإلكترونية القائمة.", desc_en: "Cancel and revoke active electronic judicial POAs.", docs_ar: "رقم الوكالة المراد فسخها، الهوية الوطنية للموكل", docs_en: "POA Number to revoke, National ID of principal", completion: "فوري" },
  { id: "najiz-verify-poa", title_ar: "التحقق من الوكالات", title_en: "Verify Validity of POAs", category_id: "najiz-justice", desc_ar: "التحقق والاستعلام عن سريان وصلاحية الوكالة الشرعية.", desc_en: "Verify and query active status and validity of judicial POAs.", docs_ar: "رقم الوكالة، رقم هوية الموكل", docs_en: "POA Number, National ID of principal", completion: "فوري" },
  { id: "najiz-lawsuit-file", title_ar: "صحيفة الدعوى", title_en: "Submit Statement of Claim", category_id: "najiz-justice", desc_ar: "إعداد ورفع صحيفة الدعوى القضائية عبر بوابة ناجز لوزارة العدل.", desc_en: "Prepare and file statement of claim via Najiz portal.", docs_ar: "تفاصيل المدعي والمدعى عليه، مستندات القضية والأسانيد", docs_en: "Plaintiff & Defendant details, supporting lawsuit evidence files", completion: "2-3 أيام عمل" },
  { id: "najiz-track-lawsuits", title_ar: "تقديم ومتابعة القضايا المتاحة إلكترونيًا", title_en: "File & Follow Up Lawsuits", category_id: "najiz-justice", desc_ar: "متابعة تحديثات الجلسات القضائية وتقديم المذكرات الجوابية.", desc_en: "Follow up court session updates and submit response memos.", docs_ar: "رقم القضية، تفويض أو وكالة سارية", docs_en: "Lawsuit Number, active delegation or POA", completion: "1-2 أيام عمل" },
  { id: "najiz-execution-req", title_ar: "طلبات التنفيذ", title_en: "Submit Execution Claims", category_id: "najiz-justice", desc_ar: "تقديم طلبات التنفيذ لتنفيذ الأحكام القضائية وسندات الأمر.", desc_en: "Submit execution claims to enforce court rulings and notes.", docs_ar: "السند التنفيذي (حكم قضائي، سند لأمر، شيك بدون رصيد)", docs_en: "Execution deed (court ruling, promissory note, bounced check)", completion: "2-3 أيام عمل" },
  { id: "najiz-inquire-lawsuits", title_ar: "الاستعلام عن القضايا", title_en: "Query Lawsuits Status", category_id: "najiz-justice", desc_ar: "الاستعلام عن تفاصيل الموعد والجلسات والأحكام الصادرة.", desc_en: "Query details of court schedules, sessions, and issued rulings.", docs_ar: "رقم القضية أو الهوية الوطنية للمستعلم عنه", docs_en: "Lawsuit Code or National ID of search target", completion: "فوري" },
  { id: "najiz-appointments", title_ar: "المواعيد", title_en: "Najiz Appointments", category_id: "najiz-justice", desc_ar: "حجز مواعيد مراجعة فروع المحاكم وكتابات العدل بالمملكة.", desc_en: "Book in-person review appointments for court branches.", docs_ar: "تحديد الدائرة القضائية والمحكمة المعنية بالموعد", docs_en: "Selected judicial division and target court details", completion: "فوري" },
  { id: "najiz-real-estate", title_ar: "الخدمات العقارية المتاحة إلكترونيًا", title_en: "Real Estate Digital Services", category_id: "najiz-justice", desc_ar: "إفراغ وتحديث الصكوك العقارية والاستعلام عن الملكية إلكترونياً.", desc_en: "Update deed records and verify property ownership online.", docs_ar: "صورة الصك العقاري، الهوية الوطنية للملاك الحاليين", docs_en: "Copy of property deed, National IDs of current owners", completion: "1-2 أيام عمل" },
  { id: "najiz-documentation", title_ar: "التوثيق", title_en: "Digital Documentation Services", category_id: "najiz-justice", desc_ar: "توثيق العقود والإفراغ وتوثيق الديون والالتزامات المالية.", desc_en: "Certify agreements, transfer deeds, and record financial dues.", docs_ar: "مستندات التعهد، موافقة الأطراف المعنية بالتوثيق", docs_en: "Undertaking documents, consent of parties involved", completion: "1-2 أيام عمل" },

  // 10. Establishment Services & Rental Contracts (Professional Assist)
  { id: "ops-waste-contracts", title_ar: "عقود النظافة", title_en: "Waste Disposal Contracts", category_id: "contracts-ops", desc_ar: "توفير وتجهيز عقود النظافة والتخلص من النفايات المعتمدة للبلدية.", desc_en: "Provide and prepare municipal-certified waste disposal contracts.", docs_ar: "تفاصيل مساحة المحل ونوع النشاط البلدي", docs_en: "Store floor area details and municipal activity type", completion: "1-2 أيام عمل" },
  { id: "ops-maintenance-contracts", title_ar: "عقود الصيانة", title_en: "Maintenance Contracts", category_id: "contracts-ops", desc_ar: "إعداد وتوقيع عقود صيانة أنظمة الحريق والسلامة والتكييف للمحلات.", desc_en: "Prepare and sign certified safety or AC system maintenance contracts.", docs_ar: "تفاصيل الأجهزة الحالية للموقع، الرخصة البلدية", docs_en: "Details of installed equipment on site, Municipal License", completion: "1-2 أيام عمل" },
  { id: "ops-operation-contracts", title_ar: "عقود التشغيل", title_en: "Operational Contracts", category_id: "contracts-ops", desc_ar: "إعداد ومراجعة عقود تشغيل وإدارة المنشآت والمرافق التجارية.", desc_en: "Draft and review operational and facility management contracts.", docs_ar: "تفاصيل شروط التشغيل والشركاء", docs_en: "Operational terms and partner identification details", completion: "3-5 أيام عمل" },
  { id: "ops-labor-contracts", title_ar: "عقود العمل", title_en: "Employment Contracts Formatting", category_id: "contracts-ops", desc_ar: "صياغة وتجهيز نماذج عقود العمل الداخلية للمؤسسات والشركات.", desc_en: "Draft internal employment contract templates for businesses.", docs_ar: "الهيكل التنظيمي للمؤسسة، لائحة العمل الفردية", docs_en: "Establishment structure, individual working bylaws", completion: "1-2 أيام عمل" },
  { id: "ops-service-contracts", title_ar: "عقود الخدمات", title_en: "Service Agreements Formatting", category_id: "contracts-ops", desc_ar: "صياغة وتدقيق عقود تقديم الخدمات المهنية والتجارية للغير.", desc_en: "Draft and audit professional service delivery contracts.", docs_ar: "نطاق العمل المتفق عليه، شروط ومواعيد التسليم", docs_en: "Agreed scope of work, delivery timelines & terms", completion: "2-3 أيام عمل" },
  { id: "ops-profile-setup", title_ar: "تجهيز ملفات المنشآت", title_en: "Company Profile Setup", category_id: "contracts-ops", desc_ar: "تجهيز وتنسيق ملفات التعريف وسيرة الأعمال للمنشآت والمؤسسات.", desc_en: "Compile and organize profiles and portfolios for businesses.", docs_ar: "قائمة الخدمات والأنشطة وشعارات الشركة", docs_en: "List of services, activities, and corporate logos", completion: "3-5 أيام عمل" },
  { id: "ops-tech-reports", title_ar: "التقارير الفنية", title_en: "Engineering Technical Reports", category_id: "contracts-ops", desc_ar: "المساعدة في استخراج التقارير الفنية الهندسية اللازمة للرخص.", desc_en: "Assistance in extracting engineering reports required for licenses.", docs_ar: "المخطط المعماري للموقع، رخصة البلدية", docs_en: "Architectural site layout sketch, Municipal License", completion: "2-3 أيام عمل" },
  { id: "ops-safety-files", title_ar: "ملفات السلامة", title_en: "Safety Files Formatting", category_id: "contracts-ops", desc_ar: "تنظيم وتوثيق ملفات الأمن والسلامة للمصانع والمنشآت التجارية.", desc_en: "Organize and document security and safety logs for factories.", docs_ar: "فواتير أدوات السلامة المعتمدة وعقود الصيانة", docs_en: "Certified safety tool invoices and maintenance contracts", completion: "2-3 أيام عمل" },
  { id: "ops-license-prep", title_ar: "تجهيز ملفات الرخص", title_en: "License Profile Preparation", category_id: "contracts-ops", desc_ar: "تجهيز وتجميع مستندات رخص البلدية والدفاع المدني لتقديم الطلبات.", desc_en: "Compile and organize municipal & civil defense license application files.", docs_ar: "السجل التجاري، عقد الإيجار، الهوية الوطنية", docs_en: "Commercial Register, Rent Contract, National ID", completion: "1-2 أيام عمل" },
  { id: "ops-inspection-follow", title_ar: "متابعة المعاينات والزيارات", title_en: "Follow Up Field Visits", category_id: "contracts-ops", desc_ar: "متابعة وإرشاد المالك لاستقبال لجان التفتيش البلدية والبيئية والمطابقة.", desc_en: "Follow up and guide owner on municipal or environmental inspections.", docs_ar: "موعد الزيارة المحدد ونوع التفتيش", docs_en: "Scheduled visit date and target inspection type", completion: "1-2 أيام عمل" },

  // 11. MODON
  { id: "modon-issue-license", title_ar: "إصدار التراخيص", title_en: "Issue MODON Licenses", category_id: "modon", desc_ar: "إصدار تراخيص البناء أو التشغيل أو التراخيص البيئية للمصانع في مدن.", desc_en: "Issue construction, operation, or environmental licenses for factories in MODON.", docs_ar: "السجل التجاري الصناعي، عقد تخصيص الأرض الصناعية", docs_en: "Industrial Commercial Register, land allocation contract", completion: "3-5 أيام عمل" },
  { id: "modon-modify-profile", title_ar: "تعديل بيانات المنشأة", title_en: "Modify MODON Profile", category_id: "modon", desc_ar: "تحديث وتعديل البيانات القانونية للمستثمر الصناعي في منصة مدن.", desc_en: "Update and modify industrial investor profile data in MODON.", docs_ar: "رقم السجل التجاري المحدث، رخصة التشغيل الصناعية", docs_en: "Updated Commercial Register, industrial operation license", completion: "2-3 أيام عمل" },
  { id: "modon-land-services", title_ar: "خدمات الأراضي الصناعية", title_en: "Industrial Land Services", category_id: "modon", desc_ar: "متابعة طلبات استئجار الأراضي الصناعية أو توسيع المصانع.", desc_en: "Follow up industrial land leasing or factory expansion requests.", docs_ar: "دراسة الجدوى الفنية للمشروع الصناعي، المخطط المعماري", docs_en: "Technical feasibility study of the industrial project, layout", completion: "3-5 أيام عمل" },
  { id: "modon-industrial-licenses", title_ar: "التراخيص الصناعية", title_en: "Industrial Operating Permits", category_id: "modon", desc_ar: "تجديد وتعديل وإصدار تراخيص التشغيل للمصانع والورش.", desc_en: "Renew, modify, and issue operating permits for factories and workshops.", docs_ar: "تقرير السلامة للدفاع المدني للموقع، شهادة إتمام البناء", docs_en: "Civil defense safety report of site, building completion cert", completion: "3-5 أيام عمل" },
  { id: "modon-equipment-reqs", title_ar: "متطلبات المعدات", title_en: "Factory Equipment Reqs", category_id: "modon", desc_ar: "تسجيل واعتماد الآلات والمعدات الثقيلة والمولدات للمصانع.", desc_en: "Register and certify machinery, heavy equipment, and generators.", docs_ar: "فواتير ومواصفات الكتالوج الفني للمعدات المستوردة", docs_en: "Invoices and technical catalog data of imported machinery", completion: "2-3 أيام عمل" },
  { id: "modon-specs", title_ar: "المواصفات الفنية", title_en: "MODON Technical Specifications", category_id: "modon", desc_ar: "مراجعة الاشتراطات والمواصفات الفنية للمصانع والمستودعات.", desc_en: "Review industrial technical requirements for factories & warehouses.", docs_ar: "المخطط الهندسي الإنشائي والكهربائي المعتمد", docs_en: "Approved architectural, structural & electrical layouts", completion: "2-3 أيام عمل" },
  { id: "modon-tech-reports", title_ar: "الملفات والتقارير الفنية", title_en: "MODON Technical Reports", category_id: "modon", desc_ar: "إعداد ورفع التقارير والملفات الفنية الهندسية المعتمدة للمصانع.", desc_en: "Compile and submit certified engineering technical reports for factories.", docs_ar: "مستندات دراسة الأثر البيئي، كروكي السلامة", docs_en: "Environmental impact assessment docs, safety layout", completion: "3-5 أيام عمل" },
  { id: "modon-track-requests", title_ar: "متابعة الطلبات والملاحظات", title_en: "Follow Up MODON Requests", category_id: "modon", desc_ar: "متابعة وحل الملاحظات الفنية والبلدية على طلبات رخص التشغيل.", desc_en: "Follow up and resolve technical or municipal remarks in MODON.", docs_ar: "رقم الطلب الإلكتروني في بوابة مدن", docs_en: "Request code in MODON digital portal", completion: "2-3 أيام عمل" },

  // 12. Chamber of Commerce
  { id: "chamber-subscribe", title_ar: "اشتراك الغرفة", title_en: "Chamber Subscription", category_id: "chamber", desc_ar: "التسجيل وفتح اشتراك جديد في الغرفة التجارية للمنشأة.", desc_en: "Register and open new subscription file in Chamber of Commerce.", docs_ar: "السجل التجاري، الهوية الوطنية للمالك", docs_en: "Commercial Register, National ID of Owner", completion: "فوري" },
  { id: "chamber-renew", title_ar: "تجديد الاشتراك", title_en: "Renew Chamber Subscription", category_id: "chamber", desc_ar: "تجديد صلاحية اشتراك الغرفة التجارية السنوي إلكترونياً.", desc_en: "Renew validity of Chamber of Commerce subscription online annually.", docs_ar: "رقم اشتراك الغرفة التجارية الحالي، السجل التجاري", docs_en: "Current Chamber subscription code, Commercial Register", completion: "فوري" },
  { id: "chamber-certify", title_ar: "تصديق المستندات", title_en: "Certify Documents", category_id: "chamber", desc_ar: "تصديق إلكتروني للخطابات والعقود والتفاويض الرسمية للشركات.", desc_en: "Certify letters, contracts, and official delegations online.", docs_ar: "مستند الخطاب مكتوب بالصيغة المعتمدة للغرفة", docs_en: "Letter text written in Chamber-approved format", completion: "فوري" },
  { id: "chamber-intro-letters", title_ar: "خطابات التعريف", title_en: "Introductory Letters", category_id: "chamber", desc_ar: "توثيق خطابات التعريف بالرواتب والموظفين المصدقة للجهات.", desc_en: "Certify introductory and salary certificate letters for employees.", docs_ar: "بيانات الموظف، تفاصيل الراتب المصدق", docs_en: "Employee details, certified salary breakdown details", completion: "فوري" },
  { id: "chamber-delegations", title_ar: "التفويضات", title_en: "Chamber Delegations", category_id: "chamber", desc_ar: "تصديق خطابات التفويض للمراجعين للجهات الحكومية والخاصة.", desc_en: "Certify representative delegation letters for review boards.", docs_ar: "بيانات الهوية الوطنية للوكيل والموكل والمهام", docs_en: "IDs of agent and principal, list of tasks delegated", completion: "فوري" },
  { id: "chamber-corporate-services", title_ar: "خدمات المنشآت", title_en: "Chamber Corporate Services", category_id: "chamber", desc_ar: "إدارة ملف المنشأة وتحديث الفئة والأنشطة المسجلة بالغرفة.", desc_en: "Manage facility profile, update category tier and active fields.", docs_ar: "السجل التجاري المحدث، الهوية للمدير المعتمد", docs_en: "Updated Commercial Register, ID of authorized manager", completion: "يوم عمل واحد" },
  { id: "chamber-extract-certs", title_ar: "استخراج الشهادات والخطابات", title_en: "Extract Chamber Certificates", category_id: "chamber", desc_ar: "طباعة واستخراج شهادة العضوية والانتساب الرسمية للغرفة.", desc_en: "Print and extract official Chamber of Commerce membership certificates.", docs_ar: "رقم اشتراك الغرفة التجارية المعتمد", docs_en: "Certified Chamber subscription number", completion: "فوري" },

  // 13. Transport Authority (TGA)
  { id: "tga-issue-license", title_ar: "إصدار تراخيص النقل", title_en: "Issue Transport Licenses", category_id: "transportation", desc_ar: "إصدار ترخيص الهيئة العامة للنقل للأنشطة اللوجستية وتأجير السيارات.", desc_en: "Issue Transport General Authority license for logistics & rental.", docs_ar: "السجل التجاري بالنشاط، عقد إيجار الموقع، التأمين", docs_en: "Commercial Register of activity, rent contract of site, insurance", completion: "3-5 أيام عمل" },
  { id: "tga-renew-license", title_ar: "تجديد تراخيص النقل", title_en: "Renew Transport Licenses", category_id: "transportation", desc_ar: "تجديد صلاحية تراخيص النقل والاشتراكات لشركات التوصيل والنقل.", desc_en: "Renew Transport General Authority licenses for logistics companies.", docs_ar: "الترخيص القديم المراد تجديده، التأمينات السارية", docs_en: "Old license to renew, active social security details", completion: "1-2 أيام عمل" },
  { id: "tga-operating-cards", title_ar: "بطاقات التشغيل", title_en: "Issue Operating Cards", category_id: "transportation", desc_ar: "إصدار بطاقات تشغيل للمركبات والشاحنات في أنشطة النقل البري.", desc_en: "Issue operating cards for trucks and cars in commercial transport.", docs_ar: "استمارة المركبة السارية، فحص دوري ساري، تأمين المركبة", docs_en: "Valid vehicle registration, valid periodic check, vehicle insurance", completion: "يوم عمل واحد" },
  { id: "tga-renew-cards", title_ar: "تجديد بطاقات التشغيل", title_en: "Renew Operating Cards", category_id: "transportation", desc_ar: "تجديد بطاقة التشغيل السنوية للمركبات والشاحنات لنقل الركاب والبضائع.", desc_en: "Renew annual operating cards for commercial passenger and cargo vehicles.", docs_ar: "رقم بطاقة التشغيل الحالية، استمارة المركبة السارية", docs_en: "Current operating card number, valid vehicle registration", completion: "فوري" },
  { id: "tga-change-cards", title_ar: "تغيير بطاقة التشغيل", title_en: "Modify Operating Card", category_id: "transportation", desc_ar: "تعديل أو نقل بيانات بطاقة التشغيل لمركبات النقل.", desc_en: "Modify or transfer operating card records of commercial vehicles.", docs_ar: "الاستمارة المحدثة، بطاقة التشغيل الحالية", docs_en: "Updated vehicle registration, current operating card", completion: "يوم عمل واحد" },
  { id: "tga-cancel-cards", title_ar: "إلغاء بطاقة التشغيل", title_en: "Cancel Operating Card", category_id: "transportation", desc_ar: "شطب وإلغاء بطاقة التشغيل المسجلة للمركبات من هيئة النقل.", desc_en: "Delete and cancel registered operating cards of transport vehicles.", docs_ar: "رقم بطاقة التشغيل المراد إلغاؤها", docs_en: "Operating card number to cancel", completion: "فوري" },
  { id: "tga-driver-cards", title_ar: "بطاقات السائقين", title_en: "Issue Driver Cards", category_id: "transportation", desc_ar: "إصدار بطاقات التشغيل المهنية لسائقي الأجرة والحافلات والشاحنات.", desc_en: "Issue professional driver cards for taxis, buses and trucks.", docs_ar: "رخصة القيادة العمومية، الهوية الوطنية أو الإقامة للسائق", docs_en: "Public driving license, National ID or Residence of driver", completion: "1-2 أيام عمل" },
  { id: "tga-corporate-services", title_ar: "خدمات منشآت النقل", title_en: "Transport Corporate Services", category_id: "transportation", desc_ar: "إدارة وتحديث بيانات ملف الشركات والمؤسسات اللوجستية بهيئة النقل.", desc_en: "Manage and update logistics company profile records at TGA.", docs_ar: "تفويض رسمي للممثل، السجل التجاري", docs_en: "Official representative authorization, Commercial Register", completion: "1-2 أيام عمل" },
  { id: "tga-compliance-reqs", title_ar: "متابعة المتطلبات", title_en: "Follow Up TGA Requirements", category_id: "transportation", desc_ar: "متابعة المتطلبات الفنية والبيئية لتراخيص النقل واللوجستيات.", desc_en: "Follow up technical and environmental requirements for transport licenses.", docs_ar: "تفاصيل متطلبات التفتيش المعتمدة", docs_en: "Details of certified inspection requirements", completion: "1-2 أيام عمل" },
  { id: "tga-inquire-bills", title_ar: "الاستعلام عن الفواتير والمخالفات", title_en: "Query TGA Bills & Penalties", category_id: "transportation", desc_ar: "الاستعلام وتسوية فواتير الهيئة وغرامات النقل والتشغيل.", desc_en: "Query and settle TGA bills, transportation penalty charges.", docs_ar: "رقم اللوحة أو رقم السجل التجاري للمنشأة", docs_en: "Plate number or Commercial Register of the entity", completion: "فوري" },
  { id: "tga-objections", title_ar: "الاعتراض على المخالفات", title_en: "Object to Transportation Violations", category_id: "transportation", desc_ar: "تقديم طلبات الاعتراض على غرامات ومخالفات الهيئة العامة للنقل.", desc_en: "Submit objection requests against Transport General Authority penalties.", docs_ar: "رقم المخالفة الصادر، مبررات الاعتراض الرسمية والأدلة", docs_en: "Violation notice code, official objection reasoning and proofs", completion: "2-4 أيام عمل" },

  // 14. Health Insurance
  { id: "insurance-check-status", title_ar: "الاستعلام عن حالة التأمين", title_en: "Inquire Insurance Status", category_id: "health-insurance", desc_ar: "الاستعلام عن صلاحية وسريان التأمين الطبي المربوط بهوية مقيم.", desc_en: "Query validity and active status of health insurance on Iqama.", docs_ar: "رقم الإقامة أو الهوية الوطنية للمستعلم عنه", docs_en: "Iqama or National ID of search target", completion: "فوري" },
  { id: "insurance-track-requests", title_ar: "متابعة حالة التأمين", title_en: "Follow Up Insurance Status", category_id: "health-insurance", desc_ar: "متابعة حالة ربط وتفعيل التأمين الطبي في مجلس الضمان الصحي.", desc_en: "Follow up medical insurance linking status in CCHI.", docs_ar: "رقم الإقامة للموظف، رقم بوليصة التأمين الطبي", docs_en: "Employee Iqama, medical insurance policy number", completion: "فوري" },
  { id: "insurance-employees", title_ar: "خدمات التأمين المرتبطة بالعمالة والمقيمين", title_en: "Workforce Medical Insurance Setup", category_id: "health-insurance", desc_ar: "المساعدة في تجهيز وربط التأمين الطبي للموظفين والعمالة الوافدة لإصدار الإقامات.", desc_en: "Assistance in arranging and linking health insurance for foreign workers.", docs_ar: "قائمة الإقامات للموظفين، تفاصيل باقة التأمين المطلوبة", docs_en: "List of employee Iqamas, required insurance plan package", completion: "1-2 أيام عمل" },
  { id: "insurance-link-staff", title_ar: "ربط الموظفين بالتأمين", title_en: "Link Employees to Policy", category_id: "health-insurance", desc_ar: "ربط الموظف بالبوليصة المعتمدة للمؤسسة إلكترونياً وتحديث مجلس الضمان.", desc_en: "Link employee to corporate medical policy and update CCHI.", docs_ar: "رقم بوليصة التأمين المعتمدة للمنشأة، بيانات الموظف", docs_en: "Corporate insurance policy number, employee data", completion: "فوري" },

  // 15. Traffic & Vehicles
  { id: "traffic-transfer-vehicle", title_ar: "نقل ملكية المركبة", title_en: "Transfer Vehicle Ownership", category_id: "traffic-vehicles", desc_ar: "إكمال ونقل ملكية المركبات والسيارات إلكترونياً للبائع والمشتري.", desc_en: "Transfer car/vehicle ownership records via Absher.", docs_ar: "فحص دوري ساري، تأمين ساري للمركبة، هويات الأطراف", docs_en: "Valid periodic check, valid vehicle insurance, IDs of parties", completion: "يوم عمل واحد" },
  { id: "traffic-istimara", title_ar: "الاستمارات", title_en: "Vehicle Registration (Istimara)", category_id: "traffic-vehicles", desc_ar: "إصدار وتجديد واستخراج بدل فاقد لاستمارات المركبات.", desc_en: "Issue, renew, and extract replacement vehicle registration (Istimara).", docs_ar: "سداد الرسوم الحكومية، تأمين ساري، فحص دوري ساري", docs_en: "Government fee payment, valid insurance, valid periodic check", completion: "فوري" },
  { id: "traffic-violations", title_ar: "المخالفات", title_en: "Traffic Violations Inquiry", category_id: "traffic-vehicles", desc_ar: "الاستعلام وتفصيل المخالفات المرورية المسجلة على المالك أو المركبات.", desc_en: "Inquire and extract breakdown of traffic violations on Owner or Cars.", docs_ar: "رقم الهوية الوطنية أو رقم السجل التجاري", docs_en: "National ID or Commercial Register of owner", completion: "فوري" },
  { id: "traffic-delegations", title_ar: "التفويض", title_en: "Vehicle Driving Delegations", category_id: "traffic-vehicles", desc_ar: "إصدار تفويض قيادة خارجي أو داخلي للمركبات عبر أبشر.", desc_en: "Issue inside/outside driving delegations for vehicles via Absher.", docs_ar: "رقم هوية السائق المفوض ورقم لوحة المركبة", docs_en: "National ID of driver, vehicle plate details", completion: "فوري" },
  { id: "traffic-corporate-services", title_ar: "خدمات المركبات والمنشآت", title_en: "Corporate Fleet Services", category_id: "traffic-vehicles", desc_ar: "إدارة أسطول سيارات الشركة والاستعلام وتجديد بيانات المركبات.", desc_en: "Manage company vehicle fleet, query and renew vehicle data.", docs_ar: "رقم المنشأة الموحد، تفويض رسمي للمدير", docs_en: "Unified facility number, official manager delegation", completion: "1-2 أيام عمل" },
  { id: "traffic-license-services", title_ar: "خدمات الرخص والقيادة", title_en: "Driving License Services", category_id: "traffic-vehicles", desc_ar: "تجديد وإصدار رخص القيادة للسيارات والشاحنات والدراجات.", desc_en: "Renew and issue driving licenses for cars, trucks, and bikes.", docs_ar: "نتيجة الفحص الطبي المعتمد، سداد المخالفات والرسوم", docs_en: "Certified medical exam result, fees and violations payment", completion: "فوري" },

  // 16. Business Investment
  { id: "invest-setup-entity", title_ar: "تأسيس المنشآت", title_en: "Establish Businesses", category_id: "investment-biz", desc_ar: "تأسيس وصياغة عقود تأسيس الشركات للمستثمرين المحليين والأجانب.", desc_en: "Establish companies and draft articles of association for investors.", docs_ar: "هويات الشركاء المقترحين، مسودة بنود التأسيس", docs_en: "IDs of proposed partners, draft articles of association", completion: "3-5 أيام عمل" },
  { id: "invest-modify-activities", title_ar: "تعديل الأنشطة", title_en: "Modify Business Activities", category_id: "investment-biz", desc_ar: "تعديل وتوسيع الأنشطة الاستثمارية والصناعية للمنشأة.", desc_en: "Modify and expand investment and industrial activities of the firm.", docs_ar: "السجل التجاري، الترخيص الصناعي أو الاستثماري الحالي", docs_en: "Commercial Register, active industrial or investment permit", completion: "2-3 أيام عمل" },
  { id: "invest-add-activities", title_ar: "إضافة الأنشطة", title_en: "Add Business Activities", category_id: "investment-biz", desc_ar: "إضافة تراخيص فرعية أو أنشطة إضافية للمستثمرين.", desc_en: "Add branch licenses or additional activities for business investors.", docs_ar: "السجل التجاري، تفاصيل الأنشطة الجديدة المطلوبة", docs_en: "Commercial Register, details of new activities requested", completion: "2-3 أيام عمل" },
  { id: "invest-open-portals", title_ar: "فتح ملفات الجهات الحكومية", title_en: "Register Government Portals", category_id: "investment-biz", desc_ar: "فتح وتفعيل ملفات المنشأة وتأسيس حسابات في الموارد والزكاة والبلدية.", desc_en: "Register and activate company profiles in HR, ZATCA, and Balady.", docs_ar: "السجل التجاري، الترخيص البلدي، العنوان الوطني للشركة", docs_en: "Commercial Register, Municipal License, National Address", completion: "2-3 أيام عمل" },
  { id: "invest-prepare-reqs", title_ar: "تجهيز المتطلبات", title_en: "Prepare Investment Reqs", category_id: "investment-biz", desc_ar: "مراجعة وتجهيز متطلبات الاستثمار الأجنبي واللوائح البلدية.", desc_en: "Review and compile requirements for foreign investment and municipal laws.", docs_ar: "المخطط المبدئي ونطاق استثمار المنشأة", docs_en: "Preliminary layout plan and company investment scope", completion: "2-3 أيام عمل" },
  { id: "invest-track-permits", title_ar: "متابعة التراخيص", title_en: "Follow Up Business Permits", category_id: "investment-biz", desc_ar: "متابعة طلبات التراخيص وتراخيص الاستثمار الصناعي بوزارة الاستثمار.", desc_en: "Follow up on license requests with the Ministry of Investment.", docs_ar: "رقم الطلب الصادر في بوابة وزارة الاستثمار", docs_en: "Issued request code in Ministry of Investment portal", completion: "2-4 أيام عمل" },
  { id: "invest-project-files", title_ar: "تجهيز ملفات المشاريع", title_en: "Project Profile Preparation", category_id: "investment-biz", desc_ar: "تجهيز وتجميع ملفات المشاريع والخطط التشغيلية والفنية المعتمدة.", desc_en: "Compile and organize project profiles, plans and designs.", docs_ar: "مسودة الخطة الفنية والتشغيلية للمشروع", docs_en: "Draft of project's technical and operational plan", completion: "3-5 أيام عمل" },
  { id: "invest-legal-studies", title_ar: "دراسة المتطلبات النظامية للنشاط", title_en: "Feasibility of Regulatory Reqs", category_id: "investment-biz", desc_ar: "دراسة وتدقيق الأنظمة واللوائح والاشتراطات النظامية المطلوبة للنشاط.", desc_en: "Study and audit statutory regulations and parameters for the business.", docs_ar: "تفاصيل قطاع النشاط المراد الاستثمار به", docs_en: "Details of active business sector target for investment", completion: "3-5 أيام عمل" }
];

// Helper to sanitize title comparison
function normalizeText(text) {
  return text
    .replace(/\s+/g, '')
    .replace(/[أإآ]/g, 'ا')
    .replace(/ة/g, 'ه')
    .replace(/ى/g, 'ي')
    .toLowerCase();
}

async function runMigration() {
  console.log("Starting catalog database migration...");

  // 1. Fetch existing categories and services
  const { data: currentCategories, error: catFetchErr } = await supabase.from('categories').select('*');
  if (catFetchErr) {
    console.error("Error loading categories:", catFetchErr);
    return;
  }
  const { data: currentServices, error: servFetchErr } = await supabase.from('services').select('*');
  if (servFetchErr) {
    console.error("Error loading services:", servFetchErr);
    return;
  }

  // 2. Map existing services' category_ids to the new ones safely
  console.log("Remapping categories for existing services...");
  for (const serv of currentServices) {
    const newCatId = categoryMapping[serv.category_id];
    if (newCatId && newCatId !== serv.category_id) {
      console.log(`Re-assigning service ${serv.id} from category ${serv.category_id} to ${newCatId}`);
      await supabase.from('services').update({ category_id: newCatId }).eq('id', serv.id);
    }
  }

  // 3. Delete old categories from the database if they are no longer in our 16
  console.log("Removing outdated categories...");
  const validCatIds = categoriesToSeed.map(c => c.id);
  for (const cat of currentCategories) {
    if (!validCatIds.includes(cat.id)) {
      console.log(`Deleting obsolete category: ${cat.id}`);
      await supabase.from('categories').delete().eq('id', cat.id);
    }
  }

  // 4. Upsert the 16 new categories
  console.log("Upserting 16 categories...");
  for (const cat of categoriesToSeed) {
    const { error } = await supabase.from('categories').upsert(cat);
    if (error) {
      console.error(`Failed to upsert category ${cat.id}:`, error);
    } else {
      console.log(`Category verified/created: ${cat.id}`);
    }
  }

  // Reload current services list for deduplication checks
  const { data: updatedServices } = await supabase.from('services').select('*');
  const existingServiceNamesNormalized = new Map(
    updatedServices.map(s => [normalizeText(s.title_ar), s])
  );

  let skippedCount = 0;
  let addedCount = 0;

  // 5. Seed new services with deduplication logic
  console.log("Upserting service items with duplicate prevention...");
  for (const s of servicesToSeed) {
    const normalizedTitleAr = normalizeText(s.title_ar);
    
    // Check if the service title or ID already exists in the catalog
    const exactMatch = updatedServices.find(item => item.id === s.id);
    const semanticMatch = existingServiceNamesNormalized.get(normalizedTitleAr);

    if (exactMatch || semanticMatch) {
      const match = exactMatch || semanticMatch;
      console.log(`Skipping duplicate service: "${s.title_ar}" (already exists as ID: ${match.id})`);
      skippedCount++;
      continue;
    }

    // Insert new service item safely
    const { error } = await supabase.from('services').insert({
      id: s.id,
      title_ar: s.title_ar,
      title_en: s.title_en,
      desc_ar: s.desc_ar,
      desc_en: s.desc_en,
      category_id: s.category_id,
      price: "حسب الاتفاق",
      docs_ar: s.docs_ar,
      docs_en: s.docs_en,
      completion_time_ar: s.completion,
      completion_time_en: s.completion,
      keywords: [s.title_ar, s.title_en, s.id],
      visible: true,
      order: 10
    });

    if (error) {
      console.error(`Failed to insert service ${s.id}:`, error);
    } else {
      console.log(`New service added: "${s.title_ar}"`);
      addedCount++;
    }
  }

  console.log(`Migration complete! Added ${addedCount} services, skipped ${skippedCount} duplicates.`);
}

runMigration();
